config/routes.rb
Medecinquebec::Application.routes.draw do
  resources :sessions, :only => [:new, :create, :destroy]
  resources :users
  resources :posts

  match '/contact', :to => 'menus#contact'
  match '/about'  , :to => 'menus#about'
  match '/help'   , :to => 'menus#help'
  match '/signup' , :to => 'users#new'
  match '/signin' , :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

root :to => "menus#home"

end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer         not null, primary key
#  title      :string(255)
#  body       :text
#  created_at :datetime
#  updated_at :datetime
#

class Post < ActiveRecord::Base
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer         not null, primary key
#  first_name :string(255)
#  last_name  :string(255)
#  email      :string(255)
#  user_type  :integer
#  created_at :datetime
#  updated_at :datetime
#

class User < ActiveRecord::Base
  # To create a virtual password attribute
  attr_accessor :password
  
  # Those attributes can be accessed from a web browser
  attr_accessible :first_name, :last_name, :email, :password, :password_confirmation
  
  validates :first_name, :presence => true,
                         :length   => { :maximum => 50 }
  
  validates :last_name,  :presence => true,
                         :length   => { :maximum => 50 }
  
  validates :email,      :presence   => true,
                         :format     => { :with => /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i},
                         :uniqueness => { :case_sensitive => false }
  
  validates :password,   :presence     => true,
                         :confirmation => true,
                         :length       => { :within => 6..40 }
                         
  before_save :encrypt_password
  
  # Return true if the user's password matches the submitted password.
  def has_password?( submitted_password )
    encrypted_password == encrypt(submitted_password)
  end
  
  def self.authenticate( email , submitted_password )
    user = self.find_by_email( email )
    return nil if user.nil?
    return user if user.has_password?(submitted_password)
    return nil  # This line is redondant but self explanatory.
  end
  
  def self.authenticate_with_salt(id, cookie_salt)
    user = find_by_id(id)
    (user && user.salt == cookie_salt) ? user : nil
  end
  
private
  
  def encrypt_password
    self.salt = make_salt unless has_password?(self.password)
    self.encrypted_password = encrypt(self.password)
  end

  def encrypt(string)
    secure_hash("#{self.salt}--#{string}")
  end

  def make_salt
    secure_hash("#{Time.now.utc}--#{self.password}")
  end

  def secure_hash(string)
    Digest::SHA2.hexdigest(string)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  def home
    @title = %(Home)
  end

  def contact
    @title = %(Contact us)
  end

  def about
    @title = %(About us)
  end

  def help
    @title = %(Help)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.xml
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.xml
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.xml
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.xml
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to(@post, :notice => 'Post was successfully created.') }
        format.xml  { render :xml => @post, :status => :created, :location => @post }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.xml
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to(@post, :notice => 'Post was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.xml
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to(posts_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @title = %(Sign in)
    render :new
  end

  def create
    user = User.authenticate(params[:session][:email],
                             params[:session][:password])
    if user.nil?
      flash.now[:error] = "Invalid email/password combination."
      @title = %(Sign in)
      render :new
    else
      sign_in user
      redirect_to user
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @title = %(Sign up)
    @user = User.new
  end
  
  def show
    @user = User.find(params[:id])
    @title = %(#{@user.first_name} #{@user.last_name})
  end

  def create
    @user = User.new(params[:user])
    if User.count < 50
      if @user.save
        flash[:success] = "Welcome to Medecin Quebec!"
        sign_in @user
        redirect_to @user
      else
        @title = %(Sign up)
        render :new
      end
    else
      flash[:message] = %(Too many users in the db)
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def sign_in(user)
    cookies.permanent.signed[:remember_token] = [user.id, user.salt]
    self.current_user = user
  end
  
  def sign_out
    cookies.delete(:remember_token)
    self.current_user = nil
  end
  
  def current_user=(user)
    @current_user = user
  end

  def current_user
    # User_from_remember_token is called the first time current_user is called.
    # On subsequent invocations returns @current_use without calling user_from_remember_token.
    @current_user ||= user_from_remember_token
  end
  
  def signed_in?
    !current_user.nil?
  end
  
private

  def user_from_remember_token
    User.authenticate_with_salt(*remember_token)
  end
  
  def remember_token
    cookies.signed[:remember_token] || [nil,nil]
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @title.nil? ? 'Medecin Quebec' : 'Medecin Quebec : ' + @title %></title>
  <link rel="stylesheet" href="http://code.jquery.com/mobile/1.0/jquery.mobile-1.0.min.css" />
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %> 
  <script src="http://code.jquery.com/jquery-1.6.4.min.js"></script>
  <script src="http://code.jquery.com/mobile/1.0/jquery.mobile-1.0.min.js"></script>
  <%= csrf_meta_tag %>
</head>
<body>
  <div data-role="page" data-add-back-btn="true">
  	<% flash.each do |key, value| %>
	  <div class="flash <%= key %>"><%= value %></div>
	<% end %>
  	<%= yield %>
	<%= debug(params) if Rails.env.development? %>
  </div>
</body>
</html>

app/views/menus/about.html.erb
<div data-role="header">
	<h1>About us</h1>
</div>

<div data-role="content">
	<p>This is the About Us page of the application to be filled later on.</p>
</div>

app/views/menus/contact.html.erb
<div data-role="header">
	<h1>Contact us</h1>
</div>

<div data-role="content">
	<p>This is the Contact Us page of the application to be filled later on.</p>
</div>

app/views/menus/help.html.erb
<div data-role="header">
	<h1>Help</h1>
</div>

<div data-role="content">
	<p>This is the help page of the application to be filled later on.</p>
</div>

app/views/menus/home.html.erb
<div data-role="header">
	<h1>Home</h1>
</div>

<div data-role="content">
	<ul data-role="listview">
		<li><%= link_to "Home"      , root_path    %></li>
		<li><%= link_to "Contact us", contact_path %></li>
		<li><%= link_to "About us"  , about_path   %></li>
		<li><%= link_to "Help"      , help_path    %></li>
		<% if signed_in? %>
			<li><%= link_to "Sign out", signout_path, :method => :delete %></li>
		<% else %>
		    <li><%= link_to "Sign in"   , signin_path  %></li>
			<li><%= link_to "Sign up"   , signup_path  %></li>
		<% end %>
	</ul>
</div>

<div data-role="footer">
	<h3><%= link_to "Home", root_path %></h3>
</div>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div data-role="header">
	<h1>Editing Post</h1>
	<%= link_to 'Delete', @post, :method => :delete, "data-icon" => "delete", "class" => "ui-btn-right" %>
</div>

<div data-role="content">
	<%= render 'form' %>
</div>

app/views/posts/index.html.erb
<div data-role="header">
	<h1>Listing posts</h1>
	<%= link_to 'Add', new_post_path, "data-icon" => "plus", "class" => "ui-btn-right" %>
</div>

<div data-role="content">
	<ul data-role="listview">
		<% @posts.each do |post| %>
		<li>
			<%= link_to post.title, post %>
			<%= link_to 'edit post', edit_post_path(post), "data-icon" => "gear" %>
		</li>
		<% end %>
	</ul>
</div>

app/views/posts/new.html.erb
<div data-role="header">
	<h1>New Post</h1>
</div>

<div data-role="content">
	<%= render 'form' %>
</div>

app/views/posts/show.html.erb
<div data-role="header">
	<h1><%= @post.title %></h1>
	<%= link_to 'Home', posts_url, "class" => "ui-btn-right" %>
</div>

<div data-role="content">
	<%= @post.body %>
</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> 
        prohibited this user from being saved:</h2>
    <p>There were problems with the following fields:</p>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages' %>
	<div class="field">
		<%= f.label :first_name %><br/>
		<%= f.text_field :first_name %>
	</div>
	<div class="field">
		<%= f.label :last_name %><br/>
		<%= f.text_field :last_name %>
	</div>
	<div class="field">
		<%= f.label :email %><br/>
		<%= f.text_field :email %>
	</div>
	<div class="field">
		<%= f.label :password %><br/>
		<%= f.password_field :password %>
	</div>
	<div class="field">
		<%= f.label :password_confirmation, "Confirmation" %><br/>
		<%= f.password_field :password_confirmation %>
	</div>
	<div class="actions">
		<%= f.submit "Sign up" %>
	</div>
<% end %>

app/views/users/new.html.erb
<div data-role="header">
	<h1>New User</h1>
</div>

<div data-role="content">
	<%= render 'form' %>
</div>

app/views/users/show.html.erb
<div data-role="header">
	<h1><%= @user.first_name + ' ' + @user.last_name + ', ' + @user.email %></h1>
	<%= link_to 'Home', root_path, "class" => "ui-btn-right" %>
</div>

<div data-role="content">
<table>
  <tr>
    <td>
      <strong>First name</strong> <%= @user.first_name %><br/>
      <strong>Last name</strong> <%= @user.last_name %><br/>
    </td>
  </tr>
</table>
</div>